spring:
  application:
    name: deal-service
  datasource:
    url: jdbc:postgresql://localhost:5432/deal
    username: postgres
    password: postgres
  profiles:
    active: dev
server:
  port: 8081