server:
  port: 8083
spring:
  application:
    name: statement
deal:
  url: http://deal:8081
logging:
  level:
    root: info
    neoflex.statement: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    enabled: true
