version: '3.8'

services:
  calculator:
    image: neoflex/calculator:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8082
      BASE_INTEREST_RATE: 0.10