name: CI Pipeline

on:
  push:
    branches: [ "feature/gateway&CI/initial" ] #В будущем исправить на main
  pull_request:
    branches: [ "feature/gateway&CI/initial" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./
          fail_ci_if_error: true


      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=./calculator/src/main/java,./deal/src/main/java,./statement/src/main/java,./dossier/src/main/java,./gateway/src/main/java
            -Dsonar.tests=./calculator/src/test/java,./deal/src/test/java,./statement/src/test/java,./dossier/src/test/java,./gateway/src/test/java
            -Dsonar.java.binaries=./calculator/target/classes,./deal/target/classes,./statement/target/classes,./dossier/target/classes,./gateway/target/classes
            -Dsonar.java.test.binaries=./calculator/target/test-classes,./deal/target/test-classes,./statement/target/test-classes,./dossier/target/test-classes,./gateway/target/test-classes
